version: '3'

vars:
  STACK_NAME: kasa-exporter

includes:
  daemon: ./etc/Taskfile.daemon.yml
  utils: ../../../common/CatalystStack.AbstractTaskFile.yml

tasks:
  install:
    desc: "Install dependencies using Poetry"
    cmds:
    - poetry install

  install_dev:
    desc: "Install development dependencies using Poetry"
    cmds:
    - poetry install --with dev

  run_tests:
    desc: "Run unit tests"
    deps: [install_dev]
    cmds:
    - poetry run python -m unittest discover -s tests

  watch:
    desc: "Run the exporter with livereload"
    cmds:
    - python -m kasa_exporter.watcher

  run:
    desc: "Run the exporter"
    cmds:
    - echo "deploying the exporter scrape config to the swarm (kasa running as daemon on node)"
    - docker stack deploy --with-registry-auth -c etc/deployment/kasa-exporter.service.yml {{.STACK_NAME}}
    - python -m kasa_exporter.exporter


  deploy:
    desc: "Run the exporter"
    cmds:
    - echo "Deploying ONLY the kasa exporter scrape config due to issue with multicast support in docker containers"
    - echo "run the IOT discover relay in a outpost on the local network to get the devices.  Use daemon install on docker host"
    - docker stack deploy --with-registry-auth -c etc/deployment/kasa-exporter.service.yml {{.STACK_NAME}}

  run-as-daemon:
    cmds:
    - nohup python -m kasa_exporter.exporter & echo $! > kasa-exporter.pid


