---
apiVersion: v1
kind: Service
metadata:
  name: kasa-exporter
  namespace: monitoring
  labels:
    app: kasa-exporter
    app.kubernetes.io/name: kasa-exporter
    app.kubernetes.io/component: exporter
spec:
  type: ClusterIP
  selector:
    app: kasa-exporter
  ports:
    - name: metrics
      port: 9200
      targetPort: metrics
      protocol: TCP
