global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/rules/*.yml'

scrape_configs:
- job_name: 'kasa_exporter_dev'
  static_configs:
  - targets: [ 'localhost:9201' ]
    labels:
      env: 'development'

- job_name: 'kasa_exporter_prod'
  static_configs:
  - targets: [ 'localhost:9200' ]
    labels:
      env: 'production'

# TODO: getting distracted, remove this later grabbign some stuff from another service dawgski
- job_name: 'syno_node_exporter'
  static_configs:
  - targets: [ '192.168.1.234:9100' ]
  